# Database configuration
quarkus.datasource.db-kind=
quarkus.datasource.username=
quarkus.datasource.password=
quarkus.datasource.jdbc.url=

quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.http.host=0.0.0.0

# AMQP configuration for request queue
amqp-host=
amqp-port=
amqp-username=
amqp-password=

# Outgoing request messages -> worker
mp.messaging.outgoing.weather-requests-out.connector=smallrye-amqp
mp.messaging.outgoing.weather-requests-out.address=weather-requests
mp.messaging.outgoing.weather-requests-out.durable=true
mp.messaging.outgoing.weather-requests-out.content-type=application/json

# Incoming response messages <- worker
mp.messaging.incoming.weather-responses-in.connector=smallrye-amqp
mp.messaging.incoming.weather-responses-in.address=weather-responses
mp.messaging.incoming.weather-responses-in.durable=true
mp.messaging.incoming.weather-responses-in.content-type=application/json
